---
- import_tasks: activate_rescue.yml

- name: Copy autosetup configuration file
  copy:
    src: "{{ hetzner_profile_file }}"
    dest: /autosetup
    owner: root
    group: root
    mode: 0644

- name: Run installimage 
  command: /root/.oldroot/nfs/install/installimage
  register: result

- name: Mount root filesystem
  mount:
    name: /mnt
    src: "{{ hetzner_root_device }}"
    fstype: xfs
    opts: noatime
    state: mounted

- name: Set ssh authorized keys
  authorized_key:
    key: "{{ item }}"
    user: root
    path: /mnt/root/.ssh/authorized_keys
    manage_dir: yes
  with_items: "{{ hetzner_authorized_keys }}"

- name: Reboot server
  shell: sleep 2 && shutdown -r now "triggered by betacloud.hetzner"
  async: 1
  poll: 0
  ignore_errors: yes

- name: Remove server from local known_hosts file
  local_action: command  /usr/bin/ssh-keygen -R {{ inventory_hostname }}
  ignore_errors: yes

- name: Waiting for server to come back
  local_action: 
    module: wait_for 
      host="{{ inventory_hostname }}"
      port=22 
      delay=10
      timeout=600
  become: false
